#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#
before_commands:
    - sudo composer self-update
    - composer install --dev

tools:

    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: [PHPUnit/*, tests/*]

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: [PHPUnit/*, tests/*]

    php_mess_detector: false

    php_analyzer:
        enabled: true
        filter:
            paths: [PHPUnit/*, tests/*]

    php_code_coverage:
        enabled: true
        filter:
            paths: [PHPUnit/*, tests/*]
