#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php:
  - 5.3
  #- 5.4
  - 5.5
  #- hhvm

#before_script:
  #- wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
  #- tar -zxvf phantomjs-1.9.7-linux-x86_64.tar.bz2 -C /usr/bin phantomjs-1.9.7-linux-x86_64/bin/phantomjs

before_install:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction
  - ./bin/bin/phantomjs -v                                  # < display PhantomJS Version

script:
  - phpunit -c ./tests/phpunit.xml.travis --testdox

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 1