#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [5.4, 5.5, 5.6]

before_script:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - ./bin/phantomjs -v                                      # < display PhantomJS Version

script:
  - phpunit -c ./tests/phpunit.xml.dist --testdox --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

# reduce commit history of git checkout
git:
  depth: 1